### ISSUE TITLE
Build correct data type of each tag

### ISSUE THREAD

**Issue by felipeelias** [salemove/jaeger-client-ruby#10]
At the moment, the Collector is building only `string` tags:

```ruby
def build_tag(name, value)
  Jaeger::Thrift::Tag.new(
    'key' => name.to_s,
    'vType' => Jaeger::Thrift::TagType::STRING,
    'vStr' => value.to_s
  )
end
```

Probably a simple `case` statement for the value would solve the issue.

**Comment by indrekj** [comment]
This has already been fixed. https://github.com/salemove/jaeger-client-ruby/blob/master/lib/jaeger/client/span/thrift_tag_builder.rb#L15

**Comment by felipeelias** [comment]
My bad, I didn't see that. Thanks!
