### ISSUE TITLE
[question] How to inject extra headers

### ISSUE THREAD

**Issue by darwin67** [salemove/jaeger-client-ruby#26]
Hi,

I'm having some trouble figuring out how to set extra headers for the injectors and extractors. Would you mind providing an example for doing so?

These are the headers I need based on https://istio.io/docs/tasks/telemetry/distributed-tracing/#understanding-what-happened
```
x-request-id
x-b3-traceid
x-b3-spanid
x-b3-parentspanid
x-b3-sampled
x-b3-flags
x-ot-span-context
```

The following example seems to be configured globally so it'll be great if there's an way of how to inject/extract extra headers into the client without me having to fork and modify the code.
```ruby
OpenTracing.global_tracer = Jaeger::Client.build(
  service_name: 'my-service',
  reporter: Jaeger::Reporters::RemoteReporter.new(
    sender: Jaeger::HttpSender.new(
      url: 'http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces',
      # headers: { 'test' => 'YOLO' }, # i won't be able to know the values beforehand
      encoder: Jaeger::Encoders::ThriftEncoder.new(service_name: 'my-service')
    ),
    flush_interval: 1
  ),
  injectors: {
    OpenTracing::FORMAT_RACK => [Jaeger::Injectors::B3RackCodec]
  },
  extractors: {
    OpenTracing::FORMAT_RACK => [Jaeger::Extractors::B3RackCodec]
  }
)
Jaeger::Samplers::Probabilistic.new(rate: 1.0)

get '/' do
  return 'hello world'
end
```

**Comment by indrekj** [comment]
Hey,

You are using the injectors/extractors correctly. B3RackCodec will add
```
x-b3-traceid
x-b3-spanid
x-b3-parentspanid
x-b3-sampled
x-b3-flags
```
headers.

I'm not familiar with Istio. Are you sure all provided headers are necessary? If so, then you have to write your own injector/extractor. See how B3RackCodec injector is written: https://github.com/salemove/jaeger-client-ruby/blob/master/lib/jaeger/injectors.rb#L39-L52

**Comment by darwin67** [comment]
Yes, all headers needs to be propagated.

I see it's using `carrier['uber-trace-id']` [here](https://github.com/salemove/jaeger-client-ruby/blob/master/lib/jaeger/injectors.rb#L16) and that needs to be `x-request-id`

I'll give it a try with a new injector then, thanks! :)
