### ISSUE TITLE
ThriftEncoder class in 0.10.0.0 is not as in git

### ISSUE THREAD

**Issue by asafsemo** [salemove/jaeger-client-ruby#27]
module Jaeger
  module Encoders
    class ThriftEncoder
      def initialize(service_name:)

tags is missing from constructor in the gem

**Comment by indrekj** [comment]
That's correct. I haven't released a new version yet. The last released version is currently https://github.com/salemove/jaeger-client-ruby/tree/v0.10.0 . the new version will require a major version bump so I will do few changes first before releasing it.
