### ISSUE TITLE
Process-level tags unsupported in rubygems version.

### ISSUE THREAD

**Issue by josh-lauer** [salemove/jaeger-client-ruby#30]
It appears that process-level tags, along with some other features, are unsupported in the latest release, but they are on master. Would it be possible for a new release to be cut and pushed to rubygems?

**Comment by indrekj** [comment]
Released v1.0.0. Let me know if anything is broken.

**Comment by josh-lauer** [comment]
Everything we care about at least seems to be working fine. Thank you!
