### ISSUE TITLE
Follows_from references does not work

### ISSUE THREAD

**Issue by danielgatis** [salemove/jaeger-client-ruby#31]
Hi!

I am trying to do an async span but it does not work. I am using the following snippet.

```ruby
span_context = OpenTracing.extract(OpenTracing::FORMAT_TEXT_MAP, meta)

OpenTracing.start_active_span(
  "JOB PERFORM #{self.class.name}",
  references: [
    OpenTracing::Reference.follows_from(span_context)
  ],
  tags: {
    'component' => 'active-job',
    'span.kind' => 'consumer',
    'job_id' => self.job_id,
    'request_id' => request_id
  }
)
```

But in jaeger my span graph shows this span like a `childOf` instead of 'followsFrom'. See in the picture.
<img width="1593" alt="Screen Shot 2019-12-14 at 22 21 41" src="https://user-images.githubusercontent.com/7380/70856731-ad673e00-1ec0-11ea-8230-61dd5e43ba5f.png">

what am I doing wrong?
Thanks.

**Comment by indrekj** [comment]
Is it different when using non-ruby libraries? From a quick glance the code you are using seems to be correct.

**Comment by danielgatis** [comment]
> Is it different when using non-ruby libraries?

If you run the `script/create_follows_from_trace` you will see the same behavior.

**Comment by danielgatis** [comment]
I think this is a bug in jaeger related to this issue (https://github.com/jaegertracing/jaeger-ui/issues/358), so I will close this ticket.
