### ISSUE TITLE
jaeger agent processor faillure

### ISSUE THREAD

**Issue by Dudesons** [salemove/jaeger-client-ruby#32]
Hi,

I'm implementing the jaeger client + opentracing in my app.
With the following code:
```
require 'jaeger/client'

OpenTracing.global_tracer = Jaeger::Client.build(
  service_name: ENV.fetch("JAEGER_SERVICE_NAME", Rails.application.class.parent_name),
  host: ENV.fetch("JAEGER_HOST", "jaeger"),
  port: 6831,
  tags: {env: ENV.fetch("JAEGER_ENV", "local"), cluster: ENV.fetch("JAEGER_CLUSTER", "local")},
  injectors: {
      OpenTracing::FORMAT_RACK => [Jaeger::Injectors::TraceContextRackCodec]
  },
  extractors: {
      OpenTracing::FORMAT_RACK => [Jaeger::Extractors::TraceContextRackCodec]
  })

require 'rack/tracer'
Rails.application.middleware.use Rack::Tracer

require 'active_record/opentracing'
ActiveRecord::OpenTracing.instrument

require 'redis/instrumentation'
Redis::Instrumentation.instrument
```

But with that I have some errors on the jaeger agent side:
```
{
   "level":"error",
   "ts":1580920392.2683513,
   "caller":"processors/thrift_processor.go:119",
   "msg":"Processor failed",
   "error":"*jaeger.Batch error reading struct: *jaeger.Span error reading struct: *jaeger.Tag error reading struct: error reading field 3: Invalid data length",
   "stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:119\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:83"
}
```

The issue is not on all my traces.

Also I'm not sure there is a relation but I can find some traces with the `trace-without-root-span`, inside the span I have some warning: `invalid parent span IDs=a6184ebb3cbe6de6; skipping clock skew adjustment`

Do you have an idea why I have this kind of errors ?

**Comment by indrekj** [comment]
Are you sure you're using TraceContext propagation everywhere? If not then remove injectors and extractors and let it use jaeger defaults. Otherwise from ruby side, it looks correct to me.

**Comment by Dudesons** [comment]
Ok I'm trying to identify which service generate this error.

**Comment by Dudesons** [comment]
I was trying some settings, but the issue seems to come from jaeger.Tag struct.
` *jaeger.Tag error reading struct: error reading field 3: Invalid data length`

Is it possible there is too many tags in these integrations:
```
require 'rack/tracer'
Rails.application.middleware.use Rack::Tracer

require 'active_record/opentracing'
ActiveRecord::OpenTracing.instrument

require 'redis/instrumentation'
Redis::Instrumentation.instrument
```

**Comment by Dudesons** [comment]
@indrekj  Do you have an idea where can be the issue with tags ?

**Comment by indrekj** [comment]
I have not used redis instrumentation before. Other two should work though we are currently not using jaeger in our production yet. If you can reproduce locally you could print out these spans here https://github.com/salemove/jaeger-client-ruby/blob/c058194f376f228640a596487f7349fdd47cadc6/lib/jaeger/encoders/thrift_encoder.rb#L55 and see if there's seems to be anything wrong. Also you may want to try adding instrumentations one by one and see when errors start to happen.

**Comment by Dudesons** [comment]
I have the error when I'm enabling activerecord or redis.
Yes he problem is local and in my infrastructure.
Sorry I don't understand what I have to do to print spans

**Comment by indrekj** [comment]
There recently were some span length fixes added. You could try the master version if you're still using this library.
