### ISSUE TITLE
Sampling rates from agent/collector?

### ISSUE THREAD

**Issue by CpuID** [salemove/jaeger-client-ruby#5]
I wonder what would be involved to allow retrieving the sampling rates from the agent/collector pool...?

Similar to how the Go client works: https://github.com/jaegertracing/jaeger-client-go/search?utf8=%E2%9C%93&q=SamplingRefreshInterval&type=

Feedback/thoughts/discussion welcome.

**Comment by CpuID** [comment]
Note: https://github.com/foodiefm/jaeger-client-ruby/commit/257025b1380aa34f53d9a169d5e0033f76e0f070 only performs client-side sampling configuration (set in your app, deploy it effectively), as opposed to https://github.com/jaegertracing/jaeger-client-go/search?utf8=%E2%9C%93&q=SamplingRefreshInterval&type= which hits the Jaeger Agent Sampling URL (HTTP 5778) to allow more adaptive/centralised sampling configuration to be passed from Jaeger itself.

**Comment by indrekj** [comment]
Basic samplers support added https://github.com/salemove/jaeger-client-ruby/commit/59f2af4e0faa65596e7b3e84a5acf82530d6b26f based on @foodiefm code. This does not involve getting the sampling rates from the server, but maybe it's now a bit easier to add. I haven't looked into it myself.

**Comment by CpuID** [comment]
> Basic samplers support added 59f2af4 based on @foodiefm code. This does not involve getting the sampling rates from the server, but maybe it's now a bit easier to add. I haven't looked into it myself.

:clap: starting somewhere is better than nothing :)

**Comment by CpuID** [comment]
🎉 thx :)
